name: Hello world

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ls
        run: echo $(ls)
    
